hegelocampus/PhilanthroTrees

- app.js
- config/.gitignore
- frontend/package-lock.json
- frontend/package.json
- models/Community.js
- routes/api/communities.js
- validation/create_community.js
> Community feature

- frontend/src/util/project_api_util.js
- routes/api/communities.js
- routes/api/projects.js
- routes/api/users.js
Refactored Project Index and Create routes below Community Routes.  Fixed some issues that would have caused validations to fail for creating Communities and Projects.
> Community reroutes

- frontend/src/components/app.jsx
- frontend/src/components/hooks/action_on_outside_click.jsx
- frontend/src/components/main/main_display.jsx
- frontend/src/components/main/top_bar/main-nav.jsx
- frontend/src/components/main/top_bar/top_bar.jsx
- frontend/src/components/main/top_bar/top_bar_user_menu.jsx
This is far from complete but this should deal with basic routing and sign out for now to make development a little more pleasant
> Implement preliminary top bar and main nav

- frontend/src/components/app.jsx
- frontend/src/components/main/main_display.jsx
- frontend/src/util/route_util.js
- routes/index.js
Favicon request error is fixed by routing the request to return a status of 204. **This will need to be removed if we want to add a favicon in the future** because it will block any request to an actually existing favicon
> fix weird routing issues and favicon request error

- frontend/src/components/main/main_display.jsx
- frontend/src/components/main/top_bar/top_bar.jsx
- frontend/src/components/main/user/invite_item.jsx
- frontend/src/components/main/user/pending_container.js
- frontend/src/components/main/user/pending_invites.jsx
- frontend/src/reducers/invite_reducer.js
- routes/api/communities.js
- routes/api/users.js
This creates the InviteAccept Form for Users to accept/decline invites.
> Send invites

- frontend/src/components/main/community/citizens_index.jsx
- frontend/src/components/main/community/community_detail.jsx
- frontend/src/components/main/user/invite_item.jsx
- frontend/src/components/main/user/pending_invites.jsx
- frontend/src/components/main/user/user_invitation.jsx
- frontend/src/components/project/create_task.jsx
- frontend/src/components/project/edit_project.jsx
- frontend/src/components/project/project.jsx
- frontend/src/components/project/synopsis.jsx
- frontend/src/components/project/task.jsx
- frontend/src/components/todo/todo_list.jsx
- frontend/src/reducers/projects_error_reducer.js
- frontend/src/stylesheets/community_details.scss
- frontend/src/stylesheets/main-nav.scss
- frontend/src/stylesheets/main_container.scss
- frontend/src/stylesheets/project_form.scss
- frontend/src/stylesheets/reset.css
- frontend/src/stylesheets/style.scss
- frontend/src/stylesheets/synopsis.scss
- frontend/src/stylesheets/task_card.scss
- frontend/src/stylesheets/todo.scss
- frontend/src/stylesheets/user.scss
- routes/api/projects.js
Adds css styling to major show and form components
> Css community

- frontend/src/components/project/task.jsx
- frontend/src/stylesheets/style.scss
- frontend/src/stylesheets/todo.scss
Small CSS styling changes.  No I don't think it actually fixes the root height issue.
> Philo demo review

- frontend/src/components/main/main_display.jsx
- frontend/src/components/project/project.jsx
- frontend/src/components/todo/todo_list.jsx
- frontend/src/stylesheets/main_container.scss
- frontend/src/stylesheets/todo.scss
Significantly changes the way the todo list is styled. Moved to sidebar so that project details are more accessible. Hope y'all like it
> Move todo list to sidebar

- frontend/src/components/main/community/community_detail.jsx
- frontend/src/components/main/community/community_form.jsx
> Fix community form

- frontend/src/actions/community_actions.js
- frontend/src/components/main/main_display.jsx
- frontend/src/components/main/top_bar/main-nav.jsx
- frontend/src/components/project/synopsis.jsx
- frontend/src/components/project/task.jsx
- frontend/src/util/community_api_util.js
- routes/api/communities.js
- routes/api/projects.js
- routes/api/users.js
Just deletes some things that are redundant or do nothing and removes extra console.logs we don't need.
> Links updates

- frontend/src/components/project/task.jsx
- frontend/src/stylesheets/task_card.scss
Change todo id to be a class. `id`'s must be unique so they should not be used for something that will appear on the page multiple times.
Scss file was updated to match
> Fix todo button styling

- frontend/src/components/main/sprites/sprite.jsx
This makes sprites look much more like plants at lower levels
> Change min rendering sprite to lvl 7

- frontend/src/components/main/main_display.jsx
- frontend/src/stylesheets/main_container.scss
- frontend/src/stylesheets/sprite.scss
- frontend/src/stylesheets/style.scss
- frontend/src/stylesheets/synopsis.scss
- frontend/src/stylesheets/task_card.scss
- frontend/src/stylesheets/theme.scss
- frontend/src/stylesheets/user.scss
Also fixes issue with background color not filling page
> Square containers and simplify color theme

- frontend/src/components/project/project.jsx
- frontend/src/components/project/task.jsx
- frontend/src/components/todo/todo_list.jsx
This should hopefully free us from todo-list errors and fetching issues
> Fix todo-list errors

- frontend/src/reducers/projects_reducer.js
- frontend/src/reducers/tasks_reducer.js
Projects and tasks now wipe state on logout
> Fix reducers to solve logout issues

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/splash/splash.jsx
- frontend/src/stylesheets/splash.scss
- frontend/src/stylesheets/style.scss
- package-lock.json
- package.json
recolor background, add social media links and icons
> Splash styling

- frontend/package.json
- frontend/yarn.lock
Adds missing packages that were breaking push to heroku
> Add missing packages

- frontend/src/stylesheets/project_form.scss
More technically gives them a margin to separate them.
> adds padding between Add Task and Edit Project button

- frontend/src/stylesheets/reset.css
> Remove focused dot border

- frontend/package.json
- frontend/src/components/splash/session/session_form.js
- frontend/src/util/render_errors.jsx
- frontend/yarn.lock
- package.json
- yarn.lock
There was a lot of extra stuff going on here that wasn't needed.
I also made the guest user object a constant and put it at the top of the file.
This also fixes a small weird bug where [object Object] was rendered on the splash on sign out
> Refactor session form to match best practices
